POST http://localhost:3000/getUsers
Content-Type: application/json

{
  "username": "exampleUsername",
  "password": "examplePassword",
  "email": "example@email.com"
}

###
PUT http://localhost:3000/api/updateProfile
Content-Type: application/json

{
  "token": "your_token_here",
  "username": "darref",
  "firstname": "Toto",
  "lastname": "Doe",
  "email": "john.doe@example.com",
  "avatar": "test"
}

###
GET http://localhost:3000/getProfile/testtoken/darref
Content-Type: application/json

###
GET http://localhost:3000/getAvatar/testtoken/darref