GET http://localhost:1337/api/userpersos
###
POST http://localhost:1337/api/userpersos
Content-Type: application/json

{
  "data": {
    "identifiant": "miro",
    "motdepasse": "Sakirdou1&",
    "email": "speedalbummyriam@gmail.com"
  }
}
